<?php
/**
 * Template Name: Strong Password Generator
 * Description: A custom template for generating strong passwords
 */


get_header(); 

?>

<header id="page-header" class="entry-header">
    <div id='stars-1'></div>
    <div id='stars-2'></div>
    <div id='stars-3'></div>
    <div id='title'>
        <?php the_title( '<h1 class="entry-title">', '</h1>' ); ?>
        <p>Innovating the Future, Today.</p>
    </div>                
</header><!-- .entry-header -->


<main id="primary" class="site-main">
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <form id="password-generator-form" method="post">
                    <div class="form-group">
                        <label for="password-length">Password Length:</label>
                        <input type="number" id="password-length" name="password-length" class="ct-input" min="8" max="64" required>
                    </div>
                    <div class="form-group">
                        <label class="text-start" for="password-options">
                        Password Options:
                        </label>
                    </div>
                    <div class="form-group">
                        <!-- Checkbox -->
                        <label class="checkbox" for="password-upper">
                        <input type="checkbox" id="password-upper" name="password-upper" checked>
                        <span class="checkmark"></span>
                        Include Upper Case (A-Z)
                        </label>
                    </div>
                    <div class="form-group">
                        <!-- Checkbox -->
                        <label class="checkbox" for="password-lower">
                        <input type="checkbox" id="password-lower" name="password-lower" checked>
                        <span class="checkmark"></span>
                        Include Lower Case (a-z)
                        </label>
                    </div>
                    <div class="form-group">
                        <!-- Checkbox -->
                        <label class="checkbox" for="password-number">
                        <input type="checkbox" id="password-number" name="password-number" checked>
                        <span class="checkmark"></span>
                        Include Numbers (0-9)
                        </label>
                    </div>
                    <div class="form-group">
                        <!-- Checkbox -->
                        <label class="checkbox" for="password-symbol">
                        <input type="checkbox" id="password-symbol" name="password-symbol">
                        <span class="checkmark"></span>
                        Include Symbols (!@#$%^&*()_+)
                        </label>
                    </div>

                    <input type="submit" class="cta" value="Generate Password">
                </form>

                <div id="password-output" class="mt-3"></div>
            </div>
            <div class="col-md-7">
                <p>Are you tired of using weak and easily guessable passwords for your online accounts? Are you worried about your personal information being compromised due to a weak password? Look no further! Our Strong Password Generator is here to help you create strong and secure passwords for all your accounts.</p>
                <p>Our password generator tool is designed to create unique and complex passwords that are difficult to crack. With just a few clicks, you can generate a password that includes a combination of uppercase and lowercase letters, numbers, and symbols. You can also choose the length of the password, giving you complete control over the complexity of your password.</p>
                <p>To get started, simply select the types of characters you want to include in your password using the checkboxes provided. Then, enter the desired length of your password in the input box. Finally, click the generate button to get your new password. It's that easy!</p>
                <p>Our Strong Password Generator is perfect for anyone who wants to protect their online accounts from hackers and identity thieves. With our tool, you can create passwords that are virtually impossible to guess or hack, giving you peace of mind and added security.</p>
                <p>So, why wait? Protect your online accounts with a strong and secure password generated by our Strong Password Generator. Get started now and keep your personal information safe and secure!</p>
            </div>
        </div>
    </div>
</main>

<?php get_footer(); ?>

<script>
    // Add event listener for form submission
    document.getElementById("password-generator-form").addEventListener("submit", function(event) {
        event.preventDefault();

        // Get form data
        var passwordLength = document.getElementById("password-length").value;
        var includeUpper = document.getElementById("password-upper").checked;
        var includeLower = document.getElementById("password-lower").checked;
        var includeNumber = document.getElementById("password-number").checked;
        var includeSymbol = document.getElementById("password-symbol").checked;

        // Generate password
        var password = generatePassword(passwordLength, includeUpper, includeLower, includeNumber, includeSymbol);

        // Display password
        document.getElementById("password-output").innerHTML = "<strong>Your Strong Password:</strong> " + password;
    });

    // Function to generate password
    function generatePassword(length, upper, lower, number, symbol) {
        var password = "";
        var characters = "";

        // Add characters based on options
        if (upper) {
            characters += "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        }
        if (lower) {
            characters += "abcdefghijklmnopqrstuvwxyz";
        }
        if (number) {
            characters += "0123456789";
        }
        if (symbol) {
            characters += "!@#$%^&*()_+";
        }

        // Generate password
        for (var i = 0; i < length; i++) {
            password += characters.charAt(Math.floor(Math.random() * characters.length));
        }

        return password;
    }

    // select the password input field
    const passwordInput = document.querySelector('#password');

    // select the copy button
    const copyButton = document.querySelector('#copy');

    // add click event listener to the copy button
    copyButton.addEventListener('click', () => {
    // select the text in the password input field
    passwordInput.select();
    
    // copy the selected text to clipboard
    document.execCommand('copy');
    
    // display a message indicating that the password has been copied
    alert('Password copied to clipboard!');
    });

</script>
